### ISSUE TITLE
Write a tutorial/blog post on how to use it

### ISSUE THREAD

**Issue by amandeepmittal** [AtilaDev-team/useCalendar#2]
Todo:
- Write a blog post/tutorial on how to use this hook with `expo-calendar` library.
- You can ask Expo folks to publish it on blog.expo.dev
- After the blog post is published, add the link to the repo -> Readme.md file

**Comment by AtilaDev** [comment]
I'll do this tomorrow.

**Comment by AtilaDev** [comment]
The document is done. I have to wait for publication.
