### ISSUE TITLE
How to Add events to the Google calendar in Android (Expo)? 

### ISSUE THREAD

**Issue by toandevnguyen** [AtilaDev-team/useCalendar#6]
The default calendar app on Android is Google Calendar. I followed your instructions, but when I click on the "add event" button, it only shows a permission grant notification and then nothing happens, no calendar shows up, no action no errors!

**Comment by thomas-hs** [comment]
Hi, I'm experiencing the same issue here as well. I can see it working on the emulator but when testing on my phone it doesn't sync with my Android's Google Calendar.

**Comment by toandevnguyen** [comment]
> Hi, I'm experiencing the same issue here as well. I can see it working on the emulator but when testing on my phone it doesn't sync with my Android's Google Calendar.

Why do I try on both a virtual machine and a real machine and the calendar still doesn't appear? ::((

**Comment by AtilaDev** [comment]
Hey! Feel free to open a pr to fix this!

**Comment by AtilaDev** [comment]
> The default calendar app on Android is Google Calendar. I followed your instructions, but when I click on the "add event" button, it only shows a permission grant notification and then nothing happens, no calendar shows up, no action no errors!

Hi dude, the hook is working as expected in both platforms: Android and iOS.
Maybe you could share your code to help you.
